version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    # depends_on:
    #   - backend
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
